### ISSUE TITLE
HoaxShell linux payload issue

### ISSUE THREAD

**Issue by oldkingcone** [t3l3machus/Villain#105]
Hello there! looks like the setup for the HoaxShell linux payload is bugged, position 2 appears to either be empty or out of range entirely.

Heres the error:

```
----------------------------------------
Exception occurred during processing of request from ('hack.the.box.ip.address', 36930)
Traceback (most recent call last):
  File "/usr/lib64/python3.10/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib64/python3.10/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.10/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.10/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/lib64/python3.10/http/server.py", line 433, in handle
    self.handle_one_request()
  File "/usr/lib64/python3.10/http/server.py", line 421, in handle_one_request
    method()
  File "[ TRUNCATED ]/Villain/Core/villain_core.py", line 1095, in do_GET
    Sessions_Manager.active_sessions[session_id]['Username'] = url_split[2]
IndexError: list index out of range
----------------------------------------
```

**Comment by t3l3machus** [comment]
@oldkingcone better late than never, I added a dirty patch for that, thanks!
