### ISSUE TITLE
issue with payload

### ISSUE THREAD

**Issue by InspiritW** [t3l3machus/Villain#81]
Villain > ----------------------------------------
Exception occurred during processing of request from ('10.10.187.15', 36078)
Traceback (most recent call last):
  File "/usr/lib/python3.11/socketserver.py", line 317, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.11/socketserver.py", line 348, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.11/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.11/socketserver.py", line 755, in __init__
    self.handle()
  File "/usr/lib/python3.11/http/server.py", line 432, in handle
    self.handle_one_request()
  File "/usr/lib/python3.11/http/server.py", line 420, in handle_one_request
    method()
  File "/root/Villain/Core/villain_core.py", line 953, in do_GET
    Sessions_manager.active_sessions[session_id]['Username'] = url_split[2]
                                                               ~~~~~~~~~^^^
IndexError: list index out of range
???

**Comment by t3l3machus** [comment]
@InspiritW This has been fixed, thanks.
